module.exports = {
  console: undefined,
  lcs: undefined,
  lcr: undefined,
  cpc: undefined,
  cpm: undefined,
  csm: undefined,
  uc: undefined,
  ca: undefined,
  ahs: undefined,
  iam: undefined,
  account: undefined,
  auth: undefined,
  ops: undefined,
  workorder: undefined,
  market: undefined,
  sms: undefined,
  isv: undefined,
  tenant: undefined,
  oms: undefined,
  buy: undefined,
  website: undefined,
  document: undefined,
}
